name: build

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:

jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install tesseract-ocr libtesseract-dev \
                libleptonica-dev libtiff-dev libjbig-dev

      - name: Copy binaries
        run: |
          mkdir tesseract-bin && cd tesseract-bin
          cp /usr/bin/tesseract .
          cp /usr/lib/x86_64-linux-gnu/libtesseract.so ./libtesseract.so.4
          cp /usr/lib/x86_64-linux-gnu/liblept.so ./liblept.so.5
          cp /usr/lib/x86_64-linux-gnu/libtiff.so ./libtiff.so.5
          cp /usr/lib/x86_64-linux-gnu/libjbig.so ./libjbig.so.0

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: tesseract-bin
          path: tesseract-bin
